import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/providers";
import { cookies } from "next/headers";
import { User } from "@/lib/store/slices/user-slice";
import UserInitializer from "@/lib/store/components/user-initializer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const userCookie = cookieStore.get("user")?.value;
  const user: User | null = userCookie ? JSON.parse(userCookie) : null;
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Providers>
          <UserInitializer user={user} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
